from django.contrib import admin

from models import *

admin.site.register( Organization)
admin.site.register( AdvertiserApplication)
admin.site.register( UserProfile)
admin.site.register( PublisherRelationship)
admin.site.register( PublisherGroup)
admin.site.register( Website)
admin.site.register( DataFeed)
admin.site.register( AdvertiserImage)
admin.site.register( Link)
admin.site.register( BannerSize)
admin.site.register( PromotionMethod)
admin.site.register( LinkPromotionType)
admin.site.register( PublisherVertical)
admin.site.register( PrivateMessage)
admin.site.register( Currency)
admin.site.register( ProgramTerm)
admin.site.register( ProgramTermAction)
admin.site.register( CommissionTier)
admin.site.register( Action)
admin.site.register( Alert)
admin.site.register( AutoDeclineCriteria)
admin.site.register( EmailCampaign)
admin.site.register( EmailCampaignCriteria)
admin.site.register( Impression)
admin.site.register( Conversion)
admin.site.register( ProcessedLog)
admin.site.register( ServerApplication)
admin.site.register( ServerApplicationReport)
admin.site.register( SmartAd)
