reports = {}
metrics = {}
dimentions = ()

REPORT_CHOICES = (("d-source,m-visits,newVisits","Visits by referrer"),
("d-hour,m-uniquePageviews","My 2nd report"))

CHART_TYPE_CHOICES = (("table","Table"),("chart-lines","Line Chart"),("chart-columns","Bar Chart"),)
metrics = {
    'Visitor':[ 'ga:bounces',
                'ga:entrances',
                'ga:exits',
                'ga:newVisits',
                'ga:pageviews',
                'ga:timeOnPage',
                'ga:timeOnSite',
                'ga:visitors',
                'ga:visits',],
    'Campaign':['ga:adClicks',
                'ga:adCost',
                'ga:CPC',
                'ga:CPM',
                'ga:CTR',
                'ga:impressions',],
    'Content':[ 'ga:uniquePageviews'],
    'Ecommerce':['ga:itemRevenue',
                'ga:itemQuantity',
                'ga:transactions',
                'ga:transactionRevenue',
                'ga:transactionShipping',
                'ga:transactionTax',
                'ga:uniquePurchases',],
    'Internal Search':[ 'ga:searchDepth',
                        'ga:searchDuration',
                        'ga:searchExits',
                        'ga:searchRefinements',
                        'ga:searchUniques',
                        'ga:searchVisits',],
    'Goals':[   'ga:goal(n)Completions',
                'ga:goalCompletionsAll',
                'ga:goal(n)Starts',
                'ga:goalStartsAll',
                'ga:goal(n)Value',
                'ga:goalValueAll',],
    'Events':[  'ga:totalEvents',
                'ga:uniqueEvents',
                'ga:eventValue',],
}
dimensions = {
    'Visitor':[ 'ga:browser',
                'ga:browserVersion',
                'ga:city',
                'ga:connectionSpeed',
                'ga:continent',
                'ga:country',
                'ga:date',
                'ga:day',
                'ga:daysSinceLastVisit',
                'ga:flashVersion',
                'ga:hostname',
                'ga:hour',
                'ga:javaEnabled',
                'ga:language',
                'ga:latitude',
                'ga:longitude',
                'ga:month',
                'ga:networkDomain',
                'ga:networkLocation',
                'ga:operatingSystem',
                'ga:operatingSystemVersion',
                'ga:pageDepth',
                'ga:region',
                'ga:screenColors',
                'ga:screenResolution',
                'ga:subContinent',
                'ga:userDefinedValue',
                'ga:visitCount',
                'ga:visitLength',
                'ga:visitorType',
                'ga:week',
                'ga:year',],
    'Campaign':['ga:adContent',
                'ga:adGroup',
                'ga:adSlot',
                'ga:adSlotPosition',
                'ga:campaign',
                'ga:keyword',
                'ga:medium',
                'ga:referralPath',
                'ga:source',],
    'Content':[ 'ga:exitPagePath',
                'ga:landingPagePath',
                'ga:pagePath',
                'ga:pageTitle',
                'ga:secondPagePath',],

    'Ecommerce':[   'ga:affiliation',
                    'ga:daysToTransaction',
                    'ga:productCategory',
                    'ga:productName',
                    'ga:productSku',
                    'ga:transactionId',
                    'ga:visitsToTransaction',],
    'Internal Search':[ 'ga:searchCategory',
                        'ga:searchDestinationPage',
                        'ga:searchKeyword',
                        'ga:searchKeywordRefinement',
                        'ga:searchStartPage',
                        'ga:searchUsed',],
    'Navigation':[  'ga:nextPagePath',
                    'ga:previousPagePath',],
    'Events':[  'ga:eventCategory',
                'ga:eventAction',
                'ga:eventLabel',],
}